version: '3.8'

services:
  sqs:
    image: softwaremill/elasticmq
    container_name: local-sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    environment:
      - JAVA_OPTS=-Dconfig.file=/opt/elasticmq.conf

  localstack:
    image: localstack/localstack:latest
    container_name: local-s3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - ./localstack/init:/docker-entrypoint-initaws.d
