# Usar a imagem do OpenJDK 17 (ou a versão do seu projeto)
FROM openjdk:17-jdk-slim

# Definir o diretório de trabalho dentro do container
WORKDIR /app

# Copiar o arquivo JAR gerado para dentro do container
COPY target/*.jar app.jar

# Expor a porta do Spring Boot (altere conforme necessário)
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]